#undef TAPPING_TERM
#define TAPPING_TERM 301

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "xmOn5/qm05zK"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 2

#define RGB_MATRIX_STARTUP_SPD 60

